const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const Core=require('../skirmish/duel-core.js');
const source=fs.readFileSync(require('node:path').join(__dirname,'../skirmish/index.html'),'utf8');
function table(name){return vm.runInNewContext(source.match(new RegExp(`const ${name}=(\\[[\\s\\S]*?\\n\\]);`))[1]);}
const catalog={hulls:table('HULLS'),terrains:table('TTYPES')};
const loadout=(hull='dreadnought',perks=['arsenal','mobility','defense'])=>({hull,perks});
const create=(seed='same',a=loadout(),b=loadout())=>Core.create(seed,[a,b],catalog);
const cmd=(s,action,payload={},slot=s.turn)=>Core.command(s,slot,{action,payload,turnId:s.turnId});
function settle(s){for(let i=0;i<2000&&s.phase==='shot';i++)Core.step(s);assert.notEqual(s.phase,'shot','shot must terminate');}

test('Artillery keeps original six hulls and five terrain generators',()=>{assert.equal(catalog.hulls.length,6);assert.equal(catalog.terrains.length,5);assert.deepEqual(create(),create());assert.notDeepEqual(create('other').terrain,create().terrain);});
test('Artillery rejects illegal loadouts, out-of-turn, invalid and duplicate shots',()=>{assert.throws(()=>create('x',loadout('bad')));const s=create();assert.equal(cmd(s,'fire',{angle:45,power:60},1),false);assert.equal(cmd(s,'fire',{angle:NaN,power:60}),false);assert.equal(cmd(s,'fire',{angle:90,power:60}),false);assert.equal(cmd(s,'fire',{angle:45,power:60,weapon:'cheat'}),false);assert.equal(cmd(s,'fire',{angle:45,power:60}),true);assert.equal(cmd(s,'fire',{angle:45,power:60}),false);settle(s);assert.equal(s.turn,1);assert.equal(Core.command(s,1,{action:'pass',turnId:1}),false);});
test('Artillery CPU calculates a real ballistic shot that damages its opponent',()=>{const s=create();s.terrain.fill(250);s.tanks.forEach(t=>t.y=238);s.wind=0;const aim=Core.cpuAim(s,0);assert.equal(cmd(s,'fire',aim),true);settle(s);assert.ok(s.tanks[1].hp<6);assert.equal(s.tanks[0].hp,6);assert.notEqual(s.terrain[590],250);});
test('Artillery fixed world survives mobile resize and snapshots preserve exact seeded continuation',()=>{const a=create();cmd(a,'fire',{angle:45,power:60});for(let i=0;i<20;i++)Core.step(a);const b=Core.publicState(a);assert.equal(b.rng,a.rng);for(let i=0;i<300;i++){Core.step(a);Core.step(b);}assert.deepEqual(Core.publicState(a),Core.publicState(b));assert.equal(a.width,720);assert.equal(a.height,346);});
test('Artillery all original math factions survive authority reconnect',()=>{const seen=new Set();for(let n=0;n<100;n++){const s=create(n);s.round=8;assert.equal(cmd(s,'math',{kind:'defense'}),true);const q=s.challenge;seen.add(q.faction);const restored=Core.publicState(s);assert.equal(restored.challenge.ans,undefined);assert.equal(cmd(restored,'answer',{id:q.id,value:Core.solveMath(q)}),true);assert.equal(restored.tanks[0].energy,2);assert.ok(restored.tanks[0].shield>0);assert.equal(cmd(restored,'answer',{id:q.id,value:Core.solveMath(q)}),false);}assert.deepEqual([...seen].sort(),['addsub','alg','frac','mult']);});
test('Artillery pause stops physics and math; timeout resolves only once',()=>{const s=create();cmd(s,'math',{kind:'defense'});s.paused=true;const before=Core.publicState(s);for(let i=0;i<100;i++)Core.step(s);assert.deepEqual(Core.publicState(s),before);s.paused=false;for(let i=0;i<610;i++)Core.step(s);assert.equal(s.phase,'aim');assert.deepEqual(s.tanks[0].mathUsed,['defense']);assert.equal(cmd(s,'math',{kind:'defense'}),false);});
test('Artillery weapon inventory, movement and abilities cannot be overspent',()=>{const s=create();s.terrain.fill(250);assert.equal(cmd(s,'ability'),false);s.tanks[0].energy=4;assert.equal(cmd(s,'ability'),true);assert.equal(s.tanks[0].fortify,2);assert.equal(cmd(s,'ability'),false);for(let i=0;i<3;i++)assert.equal(cmd(s,'move',{dir:1}),true);assert.equal(cmd(s,'move',{dir:1}),false);s.tanks[0].weapons.mega=0;assert.equal(cmd(s,'fire',{angle:45,power:50,weapon:'mega'}),false);});
test('Artillery crate collision opens original math protocol and awards 2–3 weighted loot items',()=>{const s=create('crate',loadout('dreadnought',['crates','arsenal','mobility']));s.terrain.fill(250);s.phase='shot';s.projectiles=[{x:359,y:238,vx:1,vy:0,wid:'standard',owner:0,age:10}];Core.step(s);assert.equal(s.phase,'math');assert.equal(s.challenge.kind,'crate');const q=s.challenge;assert.equal(cmd(s,'answer',{id:q.id,value:Core.solveMath(q)}),true);assert.equal(s.loot.length,3);assert.equal(s.phase,'loot');const perk=Core.PERKS.find(p=>!s.tanks[0].perks.includes(p));assert.equal(cmd(s,'collect',{perk}),true);assert.equal(s.turn,1);assert.equal(s.crateClaimed,true);});
test('Artillery Wraith cloak costs original four energy',()=>{const s=create('cloak',loadout('wraith'));assert.equal(cmd(s,'cloak'),false);s.tanks[0].energy=4;assert.equal(cmd(s,'cloak'),true);assert.equal(s.tanks[0].energy,0);assert.equal(s.tanks[0].cloak,2);assert.equal(cmd(s,'cloak'),false);});
test('Artillery Necromancer fires simulated original ghost projectiles, not guaranteed hits',()=>{const s=create('ghost',loadout('necromancer'));assert.equal(cmd(s,'ability'),true);assert.equal(s.tanks[0].ghosts.length,1);assert.equal(s.projectiles.length,1);assert.equal(s.projectiles[0].ghost,true);assert.equal(s.tanks[1].hp,6);settle(s);assert.equal(s.turn,0,'summon projectile does not consume primary shot');assert.equal(s.phase,'aim');assert.equal(cmd(s,'ability'),false);});
test('Artillery Carrier adaptive support still covers heal, ammo, reinforcement, airstrike',()=>{const make=()=>{const s=create('carrier',loadout('carrier'));s.tanks[0].energy=10;return s;};let s=make();s.tanks[0].hp=2;cmd(s,'ability');assert.equal(s.tanks[0].hp,3);s=make();const ammo=s.tanks[0].ammo;cmd(s,'ability');assert.equal(s.tanks[0].ammo,ammo+4);s=make();s.tanks[1].ghosts=[{x:500,y:200,hp:1,turns:3}];cmd(s,'ability');assert.equal(s.tanks[0].ghosts[0].isAlly,true);s=make();s.tanks[1].ghosts=[{x:500,y:200,hp:1,turns:3},{x:520,y:200,hp:1,turns:3}];cmd(s,'ability');assert.equal(s.tanks[1].hp,5);assert.equal(s.tanks[1].ghosts.length,0);});
test('Artillery finish locks commands and fresh match contains no stale projectiles, damage or terrain',()=>{const s=create();s.terrain.fill(250);s.tanks.forEach(t=>t.y=238);s.wind=0;s.tanks[1].hp=1;cmd(s,'fire',Core.cpuAim(s,0));settle(s);assert.equal(s.phase,'finished');assert.equal(s.winner,0);assert.equal(cmd(s,'pass'),false);const fresh=create();assert.equal(fresh.tanks[1].hp,6);assert.equal(fresh.projectiles.length,0);assert.equal(fresh.turnId,1);assert.equal(fresh.winner,null);assert.notDeepEqual(fresh.terrain,s.terrain);});
test('Artillery original campaign remains intact and renderer is reused by the duel',()=>{assert.match(source,/function startGame\(/);assert.match(source,/function carrierSupplyDrop\(/);assert.match(source,/drawSky\(\);drawTerrain\(\)/);assert.match(source,/drawPlayer\(\);ctx.restore\(\)/);assert.match(source,/drawProjectiles\(\);drawGhostProjs\(\)/);});
